name: 'pr-git-diff-comment-action'
description: 'sort merged commits in Specific branch'
icons: red
colos: red
inputs:
  GITHUB_TOKEN:
    description: "The GitHub token for authentication"
    required: true  # 입력을 필수로 지정
  GIT_DIFF_COMMENT_TITLE:
    description: "The title of the comment"
runs:
  using: 'node20'
  main: 'dist/index.js'
