name: "Trigger on Merge to Specific Branch"
on:
  push:
    branches:
      - test  # 머지 타겟 브랜치

jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 커밋 기록을 가져오도록 설정

      - name: Install dependencies
        run: npm install

      - name: Run interface comparison
        run: node src/actionTest.js  # index.js 파일 실행
