name: "Run on PR Merge to Test Branch"
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: write  # 리포지토리에 푸시할 수 있는 권한
  pull-requests: write

jobs:
  diff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Install dependencies
        run: npm install

      - name: Run the action
        uses: Jay-WKJun/deploy-action@release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_DIFF_COMMENT_TITLE: "배포 리스트"
