name: "Run on PR Merge to Main Branch"
on:
  pull_request:
    types: [closed]  # PR이 닫힐 때 실행
    branches:
      - test  # main 브랜치로 머지될 때만 실행

jobs:
  merge-check:
    if: github.event.pull_request.merged == true  # PR이 머지된 경우에만 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 전체 히스토리를 가져오기 위해 0으로 설정

      - name: Install dependencies
        run: npm install

      - name: Run interface comparison
        run: node src/actionTest.js  # index.js 파일 실행
