name: "Run on PR Merge to Test Branch"
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions:
  contents: write  # 리포지토리에 푸시할 수 있는 권한

jobs:
  diff-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Install dependencies
        run: npm install

      - name: Run git diff comparison
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN을 환경 변수로 설정
        run: node dist/index.js
